"""first

Revision ID: 5ebe6d3b0283
Revises: 
Create Date: 2024-12-11 10:27:21.084829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ebe6d3b0283'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('time_start', sa.Float(), nullable=False),
    sa.Column('time_end', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_tag'), 'sites', ['tag'], unique=True)
    op.create_index(op.f('ix_sites_url'), 'sites', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sites_url'), table_name='sites')
    op.drop_index(op.f('ix_sites_tag'), table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
